name: Deploy
on:
  push:
    branches:
      - main  # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps: # 自动化步骤
      - name: Checkout  # 第一步，下载代码仓库
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.2.2
        with:
          # The remote path
          remote_path: /usr/share/nginx/html
          # The remote host
          remote_host: ${{ secrets.SERVER_HOST }}
          # The remote port
          remote_port: ${{ secrets.SERVER_PORT }} # optional, default is 22
          # The remote user
          remote_user: ${{ secrets.SERVER_USER }}
          # The remote key
          remote_key: ${{ secrets.SERVER_KEY }}
            
