name: Deploy
on:
  push:
    branches:
      - master  # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps: # 自动化步骤
      - name: Checkout  # 第一步，下载代码仓库
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Server    # 第二步，推文件到服务器
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_KEY }}    # 引用Github配置，SSH私钥
          ARGS: -avz --delete --exclude='*.env' --exclude='runtime/' # rsync参数，删除服务器目录的文件，排除.env，runtime文件
          SERVER_PORT: ${{ secrets.SERVER_PORT }}  # 引用Github配置，SSH端口,默认22
          FOLDER: ./build # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SERVER_HOST }}    # 引用Github配置，服务器的host名（IP或者域名domain.com
          USERNAME: ${{ secrets.SERVER_USERNAME }} # 引用Github配置，服务器登录名
          SERVER_DESTINATION: /usr/share/nginx/html/ # 部署到服务器目标文件夹
            
